### ISSUE TITLE
Reverse Cycling from first to last

### ISSUE THREAD

**Issue by kemonprogrammer** [phibr0/cycle-through-panes#9]
Great plugin! 

I don't know if it is already implemented (to my knowledge not), but when I am on the first pane and want to reverse cycle (to the last pane), it does not work.

This could be an improvement:

### Improvement:
- When you are on the first pane
- and you press <kbd>CTRL</kbd>+ <kbd>SHIFT</kbd> + <kbd>TAB</kbd>
- You'll get to the last pane

**Comment by phibr0** [comment]
Fixed in Release 0.0.9

**Comment by paper-st** [comment]
Sadly, this still doesn't work for me in 0.0.9. 
Wouldn't it make sense to also make it work the other way around, i.e. going from the last pane to the first pane with CTRL + TAB?

Love the plugin otherwise!

**Comment by Vinzent03** [comment]
@paper-st Sorry, but I can't reproduce your issue. For me, it works in both directions, from last to first and from first to last. Could you share a video or description of your pane setup? (How many. Which pane types,..)

**Comment by paper-st** [comment]
I found my mistake: I had a pinned note on the bottom right corner in preview mode. I assumed that notes in preview mode are simply skipped over (I actually forgot that this is also a pane). When I removed it, it works as intended. 

Might be a nice improvement to just have it behave as if these notes weren't there, so one can still cycle through. Anyway, thanks for the help!

**Comment by Vinzent03** [comment]
It shouldn't be skipped, because it allows you to cycle to a preview pane and switch it to edit mode. In your case, should another `CTRL + TAB` press fixed it, because it first goes to the bottom pane and then to the start.

**Comment by paper-st** [comment]
As you said, it is not about edit/preview mode, but about having a note open in the sidebar. If there is a note there, edit mode or not, I neither can move to it nor over it. The rightmost file of the "main screen" stays active. 
I get this behaviour even if the sidebar is collapsed.

**Comment by Vinzent03** [comment]
Ah you are talking about a note in the sidebar. You didn't mention that. I thought you mean a note in the root in the bottom right corner. You are right, there is a bug. Sadly, we already fixed that, but the issue is back again. #7

**Comment by Vinzent03** [comment]
@paper-st Should again be fixed now.

**Comment by paper-st** [comment]
Great, sorry for the confusion with the sidebar. Thanks!
